### ISSUE TITLE
SR300 depth demo doesn't look like it works

### ISSUE THREAD

**Issue by gabrielstuff** [01org/depth-camera-web-demo#10]
Hi !
Nice job putting in place this demo work.
Unfortunately it shows nothing on OSX, with a SR300 and Chrome  60.0.3112.101.

No errors are displayed in the console either.

Which version did you work on ?

Thanks,

G

**Comment by astojilj** [comment]
Thanks.
OSX is not yet supported.
SR300 works out of the box on Windows but driver requires somewhat complicated installation on Linux ([librealsense documentation](https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md))- [patching](https://github.com/IntelRealSense/librealsense/blob/master/scripts/realsense-camera-formats_ubuntu-xenial-Ubuntu-hwe-4.8.0-58.63_16.04.1.patch) the kernel.
While other cameras (far range R200 and ZR300) work on ChromeOS, I have used patched ChromeOS kernel when verifying the Chrome support for SR300. Let me try to get the patch to ChromeOS  and let's track the progress using Issue #6 - I will close this issue as it has "the same cause as #6".
As of OSX support, work is currently ongoing on [Android Tango support](https://bugs.chromium.org/p/chromium/issues/detail?id=674440) and after it the OSX support is planned.
