### ISSUE TITLE
Support RealSense Depth Camera D435

### ISSUE THREAD

**Issue by doseguritan** [01org/depth-camera-web-demo#14]
Good Day,
I tried your live demo with RealSense D435 Camera. result is below.
Do I need to install or enable anything for this to work?

![error](https://user-images.githubusercontent.com/17897611/53863901-35611300-4026-11e9-87d1-e026cefaefad.PNG)

**Comment by astojilj** [comment]
We still didn't add it to a [list here](https://github.com/01org/depth-camera-web-demo/blob/e5163d5d970b75ed01e7eb76eeb26840d965cc05/depth-camera.js#L146) - meaning that we need to provide configuration parameters for this camera.
Unfortunately, we don't have D435 camera at the moment, only D435i.
I have just [changed the ](https://github.com/01org/depth-camera-web-demo/commit/ef730391b72f1dc98db81de9c68070a948b89eb3) code, using D435i calibration parameters for D435, too. As there is no other way for me to test it now, could you please verify if it works correctly? Thanks.

**Comment by doseguritan** [comment]
thanks, going to download it

**Comment by astojilj** [comment]
No need to download, sorry - could you please just reload live demo?

**Comment by doseguritan** [comment]
sorry but the result is same.

**Comment by astojilj** [comment]
I have just amend the patch. Could you please try this [live demo page](https://01org.github.io/depth-camera-web-demo/gesture/index.html)? 
Also, please use "More tools" -> "Clear Browsing Data" -> "Cached images and Files".
Thanks

**Comment by doseguritan** [comment]
what im accessing right now is this one https://01org.github.io/depth-camera-web-demo/depthdemo.html

**Comment by astojilj** [comment]
> what im accessing right now is this one https://01org.github.io/depth-camera-web-demo/depthdemo.html

I understand. Hopefully, it works after the latest patch - just to eliminate the doubt, let's use "More tools" -> "Clear Browsing Data" -> "Cached images and Files" before reloading the page.

**Comment by doseguritan** [comment]
same result sir. i think this one is because of the if statement 
`if (track.label.indexOf("430") == -1 && track.label.indexOf("415") == -1) {
      throw new Error('Background removal is supported only for Intel\u00ae RealSense\u2122 D400-Series Depth Cameras.');
    }`

need to add this `track.label.indexOf("435") == -1` after i do that i can see the stream but once i click the check it doesnt work

**Comment by astojilj** [comment]
Thanks for debugging it. Let me fix that. Are you working on Windows or on Linux?

**Comment by doseguritan** [comment]
im working on windows 10 64bit

**Comment by doseguritan** [comment]
depth-to-color-sync-render.js

```

          width = depthVideo.width; // from depthVideo.videoWidth
          height = depthVideo.height; // from depthVideo.videoHeight
```

i change the above code in my local
and my problem now is the depth distance it is too near. i only see the background,  how can i change it so that it can detect about 1 meter?

**Comment by astojilj** [comment]
Fixed with [926fd23](https://github.com/01org/depth-camera-web-demo/commit/926fd23c535e3a5a07fcfb94bf9afea0e31a9dc4). Verified on Windows 10 64-bit using Intel® RealSense™ Depth Camera D435 with the latest firmware (5.11.1.100).

**Comment by doseguritan** [comment]
thank you very much bro. its working right now.
My last question is how can i can update the depth range?

**Comment by OlalekanIsola** [comment]
Hi, i installed D345 on my jetson nano, it works well with the real viewer but does not work with cheese.I am trying to make it work as an RGB

**Comment by jungseokhong** [comment]
> Hi, i installed D345 on my jetson nano, it works well with the real viewer but does not work with cheese.I am trying to make it work as an RGB

@OlalekanIsola did you figure it out?

**Comment by OlalekanIsola** [comment]
Yes i did,Thank you

**Comment by jungseokhong** [comment]
@OlalekanIsola Can you share how you did it? I was trying to use it as a video device but it didn't appear.

**Comment by OlalekanIsola** [comment]
kinldy follow this link 
https://www.jetsonhacks.com/2019/12/22/install-realsense-camera-in-5-minutes-jetson-nano/
 use the build from source.

then navigate back to the build file and do whats in this link. Start from the cd build part.

link.https://github.com/IntelRealSense/librealsense/tree/master/wrappers/python

to import pyrealsense2 in python , copy the librealsense.so and pyrealsense.so file in the same folder as the python file.

God bless!!!
