### ISSUE TITLE
R200 camera renders  abnormally

### ISSUE THREAD

**Issue by kaixinjxq** [01org/depth-camera-web-demo#2]
Test the demo on windows 10 with Google Chrome Canary 59.0.3039.0 and R200 Depth camera(Intel(R) RealSense(TM) 3D Camera (R200) Depth (8086:0a80)), no error in the console window, but it can not render as well as SR300, the screenshot as following: 
<img width="770" alt="r200_depth" src="https://cloud.githubusercontent.com/assets/3191205/23934415/454a3a78-0980-11e7-874d-daafd7b8e306.PNG">

**Comment by Christywl** [comment]
Same issue happens on Linux 16.04 Chrome 61.0.3153.4 and Chrome OS Chrome 61.0.3147.0.

**Comment by astojilj** [comment]
This is long range camera and underexposed as the captured space is near the camera. In short, this is expected behavior and detailed explanation is given as a [comment here](https://github.com/01org/depth-camera-web-demo/issues/9#issuecomment-324536130).
