### ISSUE TITLE
The hands are not visible on Linux and Chrome OS

### ISSUE THREAD

**Issue by Christywl** [01org/depth-camera-web-demo#7]
Using `Intel RealSense SR300 camera`, test https://01org.github.io/depth-camera-web-demo/typing_in_the_air/front_capture_typing.html on `Linux 16.04 Chrome 61.0.3153.4` and `Chrome OS Chrome 61.0.3147.0`, the hands are not visible:
![linux_typing_sr300](https://user-images.githubusercontent.com/20039821/28399171-01fcf19e-6d3e-11e7-8f7b-f63fed3ef3bd.png)

**Comment by astojilj** [comment]
This camera requires specific installation on Linux/ChromeOS - patching the uvc kernel module:
https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md
Please reopen if after following the installation the problem is still visible.

**Comment by Christywl** [comment]
@astojilj , I patch the uvc kernel module on Ubuntu 16.04(**kernel 4.4.0**), it works fine. But patching the uvc kernel module **doesn't** success on Ubuntu 16.04(**kernel 4.10.0**). 
And, I see RealSense doesn't support Chrome OS in https://github.com/IntelRealSense/librealsense. So is there any way for Chrome OS?

Same result for #6
